name: Deploy Python CGI Script

on:
  push:
    branches:
      - main  # Runs this workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Upload the script to the server (via SSH or FTP)
      - name: Deploy via SCP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -r features/contact.py user@your-server.com:/var/www/cgi-bin/

      # Step 4: Set file permissions on the server
      - name: Set file permissions
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh user@your-server.com 'chmod +x /var/www/cgi-bin/contact.py'

      # Step 5: Test the deployment
      - name: Test CGI script
        run: curl http://your-server.com/cgi-bin/contact.py
